### ISSUE TITLE
当坐左边选中的时候，跑到右边后，对应项目能否隐藏，或者变灰色

### ISSUE THREAD

**Issue by ghost** [hxlniada/angular-dual-multi-select#1]
楼主你好
感谢你的这个徐昂亩
我想做个权限管理的项目

打算用楼主的这个项目用来做 权限选择的 框框

项目 有大概40多个大小权限

---

默认左边 列出所有 权限
 当我给予某个用户  【文章查看权限】后，这个权限 就从左边消失，然后出现在右边

这样，就可以很迅速明了的知道， 某个用户 有什么权限，   也可以快速明了的 取消某个用户的某个权限

---

就是想问问楼主， 以后会不会 增加这个功能， 就是当我在左边选择某个项目后，他跑到右边的同时，从左边消失

**Comment by hxlniada** [comment]
谢谢你使用我这个插件，下周我会有时间做这个

**Comment by ghost** [comment]
谢谢你写出这个项目，请问 什么时候支持angular2.0
