### ISSUE TITLE
When pushing to model filterning no longer works.

### ISSUE THREAD

**Issue by DeanMW** [hxlniada/angular-dual-multi-select#2]
Hi,

When pushing to the ng-model that populated the dual multi select I must add:

```
 object['$treeView'] = {"isChecked": ''}
```

If I do not add this it will throw errors when populating the left list. 

Also once a ng-model is created and a user pushes to this model, although the data will show up in the left side the data can no longer be filtered. Is there a way around this? I have noticed in the template there is searchLeft although modifying this does not seem to work.

**Comment by hxlniada** [comment]
Thank you for your issue, I will fix this O(∩_∩)O

**Comment by DeanMW** [comment]
Thanks :) I have also notice that the Select All button or:

```
 $scope.buttonCheckAll = $scope.options.buttonCheckAll || '全选';
```

no longer works either, I do not understand your code enough to fix this :( I've been trying for a while.

**Comment by DeanMW** [comment]
I have also noticed that getting an error in the angular tree view where I get:

```
TypeError: Cannot read property 'length' of undefined. 
   at Object.treeView.deleteDuplicated
   at Object.treeView.updatedStateByModelChange
```

**Comment by hxlniada** [comment]
I get it that you want to add new item to the left list (input-model)?
 Not easy, I am thinking for solutions

**Comment by DeanMW** [comment]
Yes. The reason for me doing this is I have a big list of over 3000 records which can take +3 seconds to load. What I am doing is creating the model and then calling an ajax method 10 times and appending the data each time. This way the user can still look at the list while its populating without having to wait for it to be fully populated,

**Comment by hxlniada** [comment]
Please update angular-dual-multi-select and angular-tree-view to latest version.
I add a new service treeViewService to apply changes.
for example.
if you want to push a new item "newItem" to input model "$scope.inputModel". 

``` javascript
$scope.inputModel.push(newItem);
treeViewService.applyChanges($scope.inputModel,  'addNewItem',  newItem);
```

best regards

**Comment by DeanMW** [comment]
This works now. Thanks a load man! I appreciate your help!
